apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: balaji1406/myweb:0.0.2
          ports:
            - containerPort: 8080
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  ports:
    - name: myweb
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: myweb
  type: LoadBalancer
